name = "FMTools"
uuid = "42d78071-9cca-4db8-9773-7f2675d446ef"
authors = ["changguo1998 <changguo1998@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SeisTools = "1a3a5297-0f7d-450c-8955-231a439346a8"
SeismicRayTrace = "1a90cdcd-02e0-4887-85dc-4804a62d2cac"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
